/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-11-09 10:47:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class clause_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js\"></script>\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <title>BE FREE</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            body{\r\n");
      out.write("                background-color: #f5f6f7;\r\n");
      out.write("                font-family: 'Gowun Dodum', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("            ul {list-style-type: none; padding: 0;}\r\n");
      out.write("            input {\r\n");
      out.write("                /*float: left;*/\r\n");
      out.write("                height: 16px;\r\n");
      out.write("                width: 16px;\r\n");
      out.write("                margin-right: 13px;\r\n");
      out.write("            }\r\n");
      out.write("            a {text-decoration: none; \r\n");
      out.write("                color: rgb(114, 114, 114);}\r\n");
      out.write("            .all {\r\n");
      out.write("                padding-top:15px;\r\n");
      out.write("                margin:0 auto;\r\n");
      out.write("                width:995px;\r\n");
      out.write("            }\r\n");
      out.write("            .name{\r\n");
      out.write("                margin: 70px 0px 0px 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .logo{\r\n");
      out.write("                display: flex;\r\n");
      out.write("                /*position : relative;*/\r\n");
      out.write("                height: 100px;\r\n");
      out.write("                /*left: 32.3%;*/\r\n");
      out.write("                /*top: 70px;*/\r\n");
      out.write("                z-index: 10;\r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            .aa{\r\n");
      out.write("                height: 400px;\r\n");
      out.write("                /* background-color: #f5f6f7; */\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                width: 600px;\r\n");
      out.write("                padding-top: 30px;\r\n");
      out.write("                 margin: 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            .login_menu > ul{\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("            }\r\n");
      out.write("            .login_icon{\r\n");
      out.write("                width: 30px;\r\n");
      out.write("                float: left;\r\n");
      out.write("                margin-left: 62px;\r\n");
      out.write("            }\r\n");
      out.write("            h2{\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                /* color: gray; */\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 110px;\r\n");
      out.write("                /*top: 236.2px; */\r\n");
      out.write("                /* right: 20%; */\r\n");
      out.write("                float: left;\r\n");
      out.write("                margin: 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .aa li{  width: 550px; margin: 0 auto; padding: 5px;}\r\n");
      out.write("\r\n");
      out.write("            /*.aa a:hover{ color:goldenrod;}*/\r\n");
      out.write("\r\n");
      out.write("            .aa2{\r\n");
      out.write("                margin:0 auto;\r\n");
      out.write("                width:470px; \r\n");
      out.write("                height: 38px;\r\n");
      out.write("                background-color: rgb(89, 161, 165);\r\n");
      out.write("                border-radius: 7px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                top: 70px;\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                line-height: 50px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: all .25s;\r\n");
      out.write("                color: white;\r\n");
      out.write("                font-size:15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .id{\r\n");
      out.write("                border-radius: 7px 7px 0px 0px;\r\n");
      out.write("                width: 457px;\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                border-color: #b8b8b8;\r\n");
      out.write("                box-shadow: none;\r\n");
      out.write("                border-style: solid;\r\n");
      out.write("            }\r\n");
      out.write("            .pw{\r\n");
      out.write("                border-radius: 0px 0px 7px 7px;\r\n");
      out.write("                width: 457px;\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                border-color: #b8b8b8;\r\n");
      out.write("                box-shadow: none;\r\n");
      out.write("                border-style: solid;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login_system{\r\n");
      out.write("                clear: both;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                top: 30px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .aa >u>a{\r\n");
      out.write("                color:gray;\r\n");
      out.write("                font-size:13px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                top: 70px;\r\n");
      out.write("            }\r\n");
      out.write("            u{\r\n");
      out.write("                position: relative;\r\n");
      out.write("                top: 70px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login_Provision{\r\n");
      out.write("                width: 600px;\r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            .aa li{\r\n");
      out.write("                width: 400px;\r\n");
      out.write("                font-size: 17px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                padding: 20px 0px 0px 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .txtarea1{\r\n");
      out.write("                width: 550px;\r\n");
      out.write("                height: 100px;\r\n");
      out.write("            }\r\n");
      out.write("            .txtarea2{\r\n");
      out.write("                width: 550px;\r\n");
      out.write("                height: 100px;\r\n");
      out.write("            }\r\n");
      out.write("            #txtarea{\r\n");
      out.write("                width: 560px;\r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            .delet{\r\n");
      out.write("                width: 250px;\r\n");
      out.write("                height: 38px;\r\n");
      out.write("                background-color: white;\r\n");
      out.write("                border: 0px solid;\r\n");
      out.write("                margin: 10px;\r\n");
      out.write("                font-size: 15px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </style>        \r\n");
      out.write("        <script>\r\n");
      out.write("            $(function(){\r\n");
      out.write("                $('.agree').css({\r\n");
      out.write("                    'width': '250px',\r\n");
      out.write("                    'height': '38px',\r\n");
      out.write("                    'background-color': 'rgb(89, 161, 165)',\r\n");
      out.write("                    'border': '0px solid',\r\n");
      out.write("                    'margin': '10px',\r\n");
      out.write("                    'cursor': 'pointer',\r\n");
      out.write("                    'transition': 'all .25s',\r\n");
      out.write("                    'color': 'white',\r\n");
      out.write("                    'font-size': '15px',\r\n");
      out.write("                   'font-weight': 'bold',\r\n");
      out.write("                    'cursor': 'pointer',\r\n");
      out.write("                    'transition': 'all .25s'\r\n");
      out.write("                }).click(function(){\r\n");
      out.write("                    var terms1 = $(\".chk_1\").is(':checked');\r\n");
      out.write("                    var terms2 = $(\".chk_2\").is(':checked');\r\n");
      out.write("                    if (terms1 == true && terms2 == true) {\r\n");
      out.write("                        location.href = \"join.jsp\"\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(\"이용 약관과 개인정보 수집 및 이용에 대한 안내를 모두 동의해주세요\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"all\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"name\">\r\n");
      out.write("                <a href=\"main.html\"><img class=\"logo\" src=\"images/BE_FREE.png\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!--<hr>-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"aa\">\r\n");
      out.write("            <form class=\"login_Provision\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"garo\"><label class=\"check1\" ><input type=\"checkbox\" class=\"chk_1\" required>HM 이용약관 동의(필수)</label></li>\r\n");
      out.write("                        <li id=\"txtarea\"><textarea rows=\"6\" cols=\"80\" class=\"txtarea1\" placeholder=\r\n");
      out.write("                            \"환영합니다.\r\n");
      out.write("HM 서비스를 이용해 주셔서 감사합니다. 본 약관은 다양한 HM 서비스를 이용과 관련하여, HM과 귀하(해당 서비스 이용을 원하는 자)의 관계를 나타내기 위한 약관입니다. HM은 귀하의 효율적인 쇼핑을 돕기 위해 서비스를 제공할 것을 약속하고 그 외 필요한 상품 정보들을 최대한 많이 제공하기 위해 노력하겠습니다.\r\n");
      out.write("HM 서비스를 이용하시거나 HM 서비스 회원으로 가입하실 경우 여러분은 본 약관 및 관련 운영 정책을 확인하거나 동의하게 되므로, 잠시 시간을 내시어 주의 깊게 살펴봐 주시기 바랍니다.\r\n");
      out.write("\r\n");
      out.write("다양한 HM 서비스를 즐겨보세요.\"\r\n");
      out.write("                            readonly></textarea></li>\r\n");
      out.write("                        <li class=\"garo\"><label class=\"check2\" ><input type=\"checkbox\" class=\"chk_2\" required>개인정보 수집 및 이용에 대한 안내(필수)</label></li>\r\n");
      out.write("                        <li id=\"txtarea\"><textarea rows=\"6\" cols=\"80\" class=\"txtarea2\" placeholder=\"\r\n");
      out.write("정보통신망법 규정에 따라 HM에 회원가입 신청하시는 분께 수집하는 개인정보의 항목, 개인정보의 수집 및 이용목적, 개인정보의 보유 및 이용기간을 안내 드리오니 자세히 읽은 후 동의하여 주시기 바랍니다.\r\n");
      out.write("\r\n");
      out.write("1. 수집하는 개인정보\r\n");
      out.write("이용자는 회원가입을 하지 않아도 정보 검색, 뉴스 보기 등 대부분의 HM 서비스를 회원과 동일하게 이용할 수 있습니다. 이용자가 메일, 캘린더, 카페, 블로그 등과 같이 개인화 혹은 회원제 서비스를 이용하기 위해 회원가입을 할 경우, HM는 서비스 이용을 위해 필요한 최소한의 개인정보를 수집합니다.\r\n");
      out.write("\r\n");
      out.write("회원가입 시점에 HM가 이용자로부터 수집하는 개인정보는 아래와 같습니다.\r\n");
      out.write("- 회원 가입 시에 ‘아이디, 비밀번호, 이름, 생년월일, 성별, 휴대전화번호’를 필수항목으로 수집합니다. 만약 이용자가 입력하는 생년월일이 만14세 미만 아동일 경우에는 법정대리인 정보(법정대리인의 이름, 생년월일, 성별, 중복가입확인정보(DI), 휴대전화번호)를 추가로 수집합니다. 그리고 선택항목으로 이메일 주소, 프로필 정보를 수집합니다.\r\n");
      out.write("- 단체아이디로 회원가입 시 단체아이디, 비밀번호, 단체이름, 이메일주소, 휴대전화번호를 필수항목으로 수집합니다. 그리고 단체 대표자명을 선택항목으로 수집합니다.\" readonly></textarea></li>\r\n");
      out.write("                        <li class=\"garo\"><label class=\"check3\"><input type=\"checkbox\" class=\"chk_3\">이벤트 등 프로모션 알림 메일 수신(선택)</label></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div>\r\n");
      out.write("                <a href=\"main.jsp\"><button class=\"delet\">취소</button></a>\r\n");
      out.write("                <button class=\"agree\">모두 동의함</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
