/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-11-10 18:41:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class company_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <title>BE FREE</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            body { margin:0 auto; padding:20px 0 0 0; font-family: 'Gowun Dodum', sans-serif;}\r\n");
      out.write("            li { display: inline-block; list-style: none; }\r\n");
      out.write("            a { text-decoration: none; color:black;}\r\n");
      out.write("            header{ display: inline-block; width: 1400px; margin: 0 auto;}\r\n");
      out.write("            .hd { \r\n");
      out.write("                background-image: url('images/town_2.jpg');\r\n");
      out.write("                background-size:over;\r\n");
      out.write("                background-size:100% 100%;\r\n");
      out.write("                background-attachment: fixed;\r\n");
      out.write("                width:1400px;\r\n");
      out.write("                height:300px;\r\n");
      out.write("                background-repeat: no-repeat;\r\n");
      out.write("                margin-top:-20px;\r\n");
      out.write("            }\r\n");
      out.write("            .main{\r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .logo{\r\n");
      out.write("                /*margin-top: 30px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                position : relative;*/\r\n");
      out.write("                height: 100px;\r\n");
      out.write("                /*left: 7%*/\r\n");
      out.write("            }\r\n");
      out.write("            .login { margin-right: 62px; /*float: right;*/ }\r\n");
      out.write("            header ul{ text-align: right; }\r\n");
      out.write("            .p { \r\n");
      out.write("                height:60px;\r\n");
      out.write("                z-index: 1;\r\n");
      out.write("                width:1500px; \r\n");
      out.write("                margin:0; \r\n");
      out.write("                padding:0;\r\n");
      out.write("             }\r\n");
      out.write("             nav {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                /* background: black; */\r\n");
      out.write("                margin: 0 auto;\r\n");
      out.write("                /* width: 95%; */\r\n");
      out.write("                /* position: absolute; */\r\n");
      out.write("                /* left: 10%;*/\r\n");
      out.write("            }\r\n");
      out.write("            ul, li {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                list-style: none;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            nav > ul > li{\r\n");
      out.write("                width: 130px;\r\n");
      out.write("            }\r\n");
      out.write("            .se{\r\n");
      out.write("                background-color: white;\r\n");
      out.write("                /*position: absolute;\r\n");
      out.write("                top: 733px;\r\n");
      out.write("                left: 4%;*/\r\n");
      out.write("	            margin: 0 auto;\r\n");
      out.write("            }\r\n");
      out.write("            #main-menu{\r\n");
      out.write("                /*background: black;*/\r\n");
      out.write("                height: 40px;\r\n");
      out.write("                /* position: relative; */\r\n");
      out.write("                /* top: 50%; */\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                margin: 35px 0px 0px 20px;\r\n");
      out.write("                float: right;\r\n");
      out.write("                width: 810px;\r\n");
      out.write("            }\r\n");
      out.write("            #main-menu > li > a {\r\n");
      out.write("                /*color:white;*/\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                line-height: 39px;\r\n");
      out.write("                padding: 0px 20px 0px 15px;\r\n");
      out.write("                text-shadow: 1px 1px 1px white(0, 0, 0, 0.39);\r\n");
      out.write("                width: 90px;\r\n");
      out.write("                float: right;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            #main-menu > li::before{\r\n");
      out.write("                content: \"|\";\r\n");
      out.write("                float: right;\r\n");
      out.write("                display: block;\r\n");
      out.write("                margin-top: 7.7px;\r\n");
      out.write("            }\r\n");
      out.write("            #main-menu > li:last-child::before{\r\n");
      out.write("                content: \"\";\r\n");
      out.write("            }\r\n");
      out.write("            #main-menu > li> .logo{\r\n");
      out.write("                width: 120px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #sub-menu {\r\n");
      out.write("                width:120px;\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                visibility: hidden;\r\n");
      out.write("                background-color: rgba(255, 255, 255, 0.801);\r\n");
      out.write("                border-top: 2px solid gold;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                top: 74px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #sub-menu > li {\r\n");
      out.write("                display: block;\r\n");
      out.write("                font-size:13px;\r\n");
      out.write("                padding: 10px 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #main-menu > li:hover #sub-menu {\r\n");
      out.write("                z-index: 1;\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                visibility: visible;\r\n");
      out.write("            }\r\n");
      out.write("            #sub-menu > li > a:hover { text-decoration:underline; color:gray; }\r\n");
      out.write("            .event ul li { list-style: none; display: inline-block; }\r\n");
      out.write("            section div img { width: 100%; } \r\n");
      out.write("            .ment {\r\n");
      out.write("                margin :0 auto;\r\n");
      out.write("                float:left;\r\n");
      out.write("                width:100%;\r\n");
      out.write("                font-size:100px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top:100px;\r\n");
      out.write("                color:rgb(255, 255, 255);\r\n");
      out.write("                font-size: 70px;\r\n");
      out.write("            }\r\n");
      out.write("            section{width:1400px;margin:0 auto; padding-top:50px;}\r\n");
      out.write("            .a1{ text-align: center; font-weight: bold; font-size:30px;}\r\n");
      out.write("           /*.a2{background-color:gray; color:white; border-bottom: 2px solid black; padding:5px; margin-top:10px;}*/\r\n");
      out.write("            .wrap {position: absolute;left: 0;bottom: 40px;width: 288px;height: 132px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}\r\n");
      out.write("            .wrap * {padding: 0;margin: 0;}\r\n");
      out.write("            .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}\r\n");
      out.write("            .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}\r\n");
      out.write("            .info .title {padding: 5px 0 0 10px;height: 30px;background: rgb(17, 38, 141);border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold; color: #fff;}\r\n");
      out.write("            .info .close {position: absolute;top: 10px;right: 10px;color: rgb(255, 255, 255);width: 17px;height: 17px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}\r\n");
      out.write("            .info .close:hover {cursor: pointer;}\r\n");
      out.write("            .info .body {position: relative;overflow: hidden;}\r\n");
      out.write("            .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}\r\n");
      out.write("            .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}\r\n");
      out.write("            .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}\r\n");
      out.write("            .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}\r\n");
      out.write("            .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}\r\n");
      out.write("            .info .link {color: #5085BB;}\r\n");
      out.write("            footer{\r\n");
      out.write("                clear:both;\r\n");
      out.write("                margin:0 auto;\r\n");
      out.write("                /*background-color: rgb(22, 20, 20);*/\r\n");
      out.write("                color:white;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                /*padding:15px;*/\r\n");
      out.write("                font-size: 12px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                width: 1350px;\r\n");
      out.write("                bottom: 0;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                border-bottom: 100px solid black;\r\n");
      out.write("				border-right: 25px solid transparent;\r\n");
      out.write("				border-left: 25px solid transparent;\r\n");
      out.write("				height: 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_list{\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .recommend_plan{\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                /*text-align: center;*/\r\n");
      out.write("                margin: 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_section{\r\n");
      out.write("                float: left;\r\n");
      out.write("                /*width: 300px;\r\n");
      out.write("                box-shadow: 5px 5px 5px gray;\r\n");
      out.write("                border: 1px solid rgb(184, 184, 184);\r\n");
      out.write("                border-radius: 5px;*/\r\n");
      out.write("                margin: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_btm_like{\r\n");
      out.write("                text-align: right;\r\n");
      out.write("                padding: 10px 20px 10px 10px;\r\n");
      out.write("                border-top: 1px solid rgb(184, 184, 184);\r\n");
      out.write("            }\r\n");
      out.write("            .item_title{\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                margin: 0px 0px 0px 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_plan{\r\n");
      out.write("                margin: 0px 0px 16px 0px;\r\n");
      out.write("                clear: left;\r\n");
      out.write("                text-align: left;\r\n");
      out.write("            }\r\n");
      out.write("            .item_img{\r\n");
      out.write("                margin: 20px;\r\n");
      out.write("                width: 200px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .item_list2{\r\n");
      out.write("                width: 1400px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 70px;\r\n");
      out.write("            }\r\n");
      out.write("            .table_travle{\r\n");
      out.write("                margin-left: auto;\r\n");
      out.write("                margin-right: auto;\r\n");
      out.write("            }\r\n");
      out.write("            .travle{\r\n");
      out.write("                /*border: 1px solid gray;*/\r\n");
      out.write("                padding-right: 60px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_section2{\r\n");
      out.write("                float: left;\r\n");
      out.write("                /*width: 240px;*/\r\n");
      out.write("                /*box-shadow: 5px 5px 5px gray;*/\r\n");
      out.write("                border: 1px solid rgb(184, 184, 184);\r\n");
      out.write("                border-radius: 5px;\r\n");
      out.write("                margin: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_section3{\r\n");
      out.write("                float: left;\r\n");
      out.write("                /*width: 240px;*/\r\n");
      out.write("                /*box-shadow: 5px 5px 5px gray;\r\n");
      out.write("                border: 1px solid rgb(184, 184, 184);\r\n");
      out.write("                border-radius: 5px;*/\r\n");
      out.write("                margin: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_title2{\r\n");
      out.write("                margin: 0px 0px 20px 0px;\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_btm_like2{\r\n");
      out.write("                text-align: right;\r\n");
      out.write("                padding: 10px 20px 10px 10px;\r\n");
      out.write("                border-top: 1px solid rgb(184, 184, 184);\r\n");
      out.write("            }\r\n");
      out.write("            .hash{\r\n");
      out.write("                /*width: 250px;*/\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                /*border: 1px solid rgb(240, 240, 240);\r\n");
      out.write("                border-radius: 150px;\r\n");
      out.write("                background-color: rgb(240, 240, 240);*/\r\n");
      out.write("            }\r\n");
      out.write("            .item_top_jeju{\r\n");
      out.write("                margin-top: 45px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_title{\r\n");
      out.write("                font-size: 40px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                font-family: 'Black Han Sans', sans-serif;\r\n");
      out.write("                color: rgb(255, 255, 255);\r\n");
      out.write("                -webkit-text-stroke-width: 0.5px;\r\n");
      out.write("                -webkit-text-stroke-color: rgb(0, 0, 0);\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("            .item_sub{\r\n");
      out.write("                font-size: 40px;\r\n");
      out.write("                font-family: 'Black Han Sans', sans-serif;\r\n");
      out.write("                color: black;\r\n");
      out.write("                -webkit-text-stroke-width: 0px;\r\n");
      out.write("                margin: 0px 0px 0px 12px;\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("            .back{\r\n");
      out.write("                background: linear-gradient(to right, #0052d4,#4364f7,#6fb1fc);\r\n");
      out.write("                height: 44px;\r\n");
      out.write("                padding: 5px;\r\n");
      out.write("            }\r\n");
      out.write("            .logo_img{\r\n");
      out.write("                width: 390px;\r\n");
      out.write("                padding: 74px 10px 74px 10px;\r\n");
      out.write("            }\r\n");
      out.write("            .site_logo{\r\n");
      out.write("                font-size: 40px;\r\n");
      out.write("                font-family: 'Black Han Sans', sans-serif;\r\n");
      out.write("                /*background: linear-gradient(to right top, #0052d4,#4364f7,#6fb1fc);\r\n");
      out.write("                color: transparent;\r\n");
      out.write("                -webkit-background-clip: text;\r\n");
      out.write("                -webkit-text-stroke-width: 0px;*/\r\n");
      out.write("                color: black;\r\n");
      out.write("                margin: 0px 0px 0px 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .object_logo{\r\n");
      out.write("                font-size: 40px;\r\n");
      out.write("                font-family: 'Black Han Sans', sans-serif;\r\n");
      out.write("                /*background: linear-gradient(to right top, #0052d4,#4364f7,#6fb1fc);\r\n");
      out.write("                color: transparent;\r\n");
      out.write("                -webkit-background-clip: text;\r\n");
      out.write("                -webkit-text-stroke-width: 0px;*/\r\n");
      out.write("                color: black;\r\n");
      out.write("                margin: 0px 0px 0px 0px;\r\n");
      out.write("            }\r\n");
      out.write("            .logo_img3{\r\n");
      out.write("                width: 350px;\r\n");
      out.write("            }\r\n");
      out.write("            .item_list3{\r\n");
      out.write("                width: 1400px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 70px;\r\n");
      out.write("            }\r\n");
      out.write("            .table_site{\r\n");
      out.write("                margin-left: auto;\r\n");
      out.write("                margin-right: auto;\r\n");
      out.write("            }\r\n");
      out.write("            .a2{\r\n");
      out.write("                font-size: 40px;\r\n");
      out.write("                font-family: 'Black Han Sans', sans-serif;\r\n");
      out.write("                /*background: linear-gradient(to right top, #0052d4,#4364f7,#6fb1fc);\r\n");
      out.write("                color: transparent;\r\n");
      out.write("                -webkit-background-clip: text;\r\n");
      out.write("                -webkit-text-stroke-width: 0px;*/\r\n");
      out.write("                color: black;\r\n");
      out.write("                margin: 0px 0px 0px 0px;\r\n");
      out.write("            }\r\n");
      out.write("        </style> \r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            /*\r\n");
      out.write("            var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = { \r\n");
      out.write("        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표\r\n");
      out.write("        level: 3 // 지도의 확대 레벨\r\n");
      out.write("    };  \r\n");
      out.write("\r\n");
      out.write("var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("    \r\n");
      out.write("// 지도타입 컨트롤의 지도 또는 스카이뷰 버튼을 클릭하면 호출되어 지도타입을 바꾸는 함수입니다\r\n");
      out.write("function setMapType(maptype) { \r\n");
      out.write("    var roadmapControl = document.getElementById('btnRoadmap');\r\n");
      out.write("    var skyviewControl = document.getElementById('btnSkyview'); \r\n");
      out.write("    if (maptype === 'roadmap') {\r\n");
      out.write("        map.setMapTypeId(kakao.maps.MapTypeId.ROADMAP);    \r\n");
      out.write("        roadmapControl.className = 'selected_btn';\r\n");
      out.write("        skyviewControl.className = 'btn';\r\n");
      out.write("    } else {\r\n");
      out.write("        map.setMapTypeId(kakao.maps.MapTypeId.HYBRID);    \r\n");
      out.write("        skyviewControl.className = 'selected_btn';\r\n");
      out.write("        roadmapControl.className = 'btn';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 지도 확대, 축소 컨트롤에서 확대 버튼을 누르면 호출되어 지도를 확대하는 함수입니다\r\n");
      out.write("function zoomIn() {\r\n");
      out.write("    map.setLevel(map.getLevel() - 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 지도 확대, 축소 컨트롤에서 축소 버튼을 누르면 호출되어 지도를 확대하는 함수입니다\r\n");
      out.write("function zoomOut() {\r\n");
      out.write("    map.setLevel(map.getLevel() + 1);\r\n");
      out.write("}*/\r\n");
      out.write("        </script>\r\n");
      out.write("       \r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"all\">\r\n");
      out.write("            <div class=\"main\">\r\n");
      out.write("                <header>\r\n");
      out.write("                    <div class=\"name\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <ul class=\"login\">\r\n");
      out.write("                        <li><a href=\"login.jsp\">로그인</a></li> &nbsp;\r\n");
      out.write("                        <li><a href=\"clause.jsp\">회원가입</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                \r\n");
      out.write("                    <nav>\r\n");
      out.write("                        <div class=\"title_menu\">\r\n");
      out.write("                            <a href=\"main.jsp\"><img class=\"logo\" src=\"images/BE_FREE.png\"></a>\r\n");
      out.write("                            <ul id=\"main-menu\">\r\n");
      out.write("                                <li><a href=\"회사소개.html\">BE FREE란</a></li>\r\n");
      out.write("                                <li><a href=\"#\">관광지</a></li>\r\n");
      out.write("                                <li><a href=\"#\">추천여행지</a>\r\n");
      out.write("                                    <ul id=\"sub-menu\">\r\n");
      out.write("                                        <li><a href=\"문의하기.html\">추천여행지</a></li>\r\n");
      out.write("                                        <li><a href=\"공지사항.html\">추천여행일정</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"#\">일정만들기</a></li>\r\n");
      out.write("                                <li><a href=\"#\">게시판</a>\r\n");
      out.write("                                    <ul id=\"sub-menu\">\r\n");
      out.write("                                        <li><a href=\"notice.jsp\">공지사항</a></li>\r\n");
      out.write("                                        <li><a href=\"Q&A.jsp\">Q&A</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"#\">나의 저장소</a>\r\n");
      out.write("                                    <ul id=\"sub-menu\">\r\n");
      out.write("                                        <li><a href=\"나의찜목록.html\">나의 찜 목록</a></li>\r\n");
      out.write("                                        <li><a href=\"나의여행일정.html\">나의 여행 일정</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <div class=\"hd\">\r\n");
      out.write("                        <div class=\"ment\">\r\n");
      out.write("                          BE FREE\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </header>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"se\">\r\n");
      out.write("                <section>\r\n");
      out.write("                    <div class=\"item_list\">\r\n");
      out.write("                        <dd class=\"recommend_plan\">\r\n");
      out.write("                            <dl class=\"item_section\">\r\n");
      out.write("                                <dt class=\"item_top\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <img src=\"images/jejudo/jejudo.png\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </dt>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"item_section\">\r\n");
      out.write("                                <dt class=\"item_top_jeju\">\r\n");
      out.write("                                    <div class=\"back\"><p class=\"item_title\">제주도의 다양한 </p><p class=\"item_sub\">명소</p></div><br>\r\n");
      out.write("                                    <p class=\"item_plan\">BE FREE 사이트는 제주도의 다양한 장소를 담고 있습니다.<br>\r\n");
      out.write("                                        관광지, 테마파크, 박물관ㆍㆍㆍ 여러분의 취향껏 살펴보세요.<br>\r\n");
      out.write("                                        복잡하고 바쁜 나날들 속의 작은 즐거움이 될 수 있도록 더더욱 좋은 정보를 제공하는 사이트가 되도록 노력하겠습니다. </p>\r\n");
      out.write("                                </dt>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </dd>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"item_list2\">\r\n");
      out.write("                        <dd class=\"recommend_travle\">\r\n");
      out.write("                            <table class=\"table_travle\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"travle\">\r\n");
      out.write("                                        <dl class=\"item_section2\">\r\n");
      out.write("                                            <dt class=\"item_top\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img src=\"images/BE_FREE.png\" class=\"logo_img\">\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </dt>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"hash\">\r\n");
      out.write("                                        <p class=\"site_logo\">사이트 로고</p><br>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                        <p> 'BE FREE'는 '자유롭다'라는 의미를 가지고 있습니다.<br>\r\n");
      out.write("                                            여러분이 즐겁고 자유로운 여행을 즐길 수 있도록 노력하는 기업이 되겠습니다.</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </dd>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item_list3\">\r\n");
      out.write("                        <dd class=\"site_object\">\r\n");
      out.write("                            <table class=\"table_site\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td class=\"travle\">\r\n");
      out.write("                                        <p class=\"object_logo\">사이트 목적</p><br>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                        <p> 여려분이 계획적이고 체계적인 여행 일정을 짤 수 있도록 도움으로써<br>\r\n");
      out.write("                                            알차고 보람된 여행이 될 수 있도록 하겠습니다.\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"hash\">\r\n");
      out.write("                                        <dl class=\"item_section3\">\r\n");
      out.write("                                            <dt class=\"item_top3\">\r\n");
      out.write("                                                    <img src=\"images/site_object.png\" class=\"logo_img3\">\r\n");
      out.write("                                            </dt>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </dd>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--p class=\"a1\">저희 BE FREE 사이트에 오신걸 환영합니다.</p><br>\r\n");
      out.write("                    <p class=\"a2\">의미</p>\r\n");
      out.write("                    <p> 'BE FREE'는 '자유롭다'라는 의미를 가지고 있습니다.<br>\r\n");
      out.write("                        여러분이 즐겁고 자유로운 여행을 즐길 수 있도록 노력하는 기업이 되겠습니다.</p>\r\n");
      out.write("                    <br><br>\r\n");
      out.write("                    <p class=\"a2\">목적</p>\r\n");
      out.write("                    <p> 여려분이 계획적이고 체계적인 여행 일정을 짤 수 있도록 도움으로써<br>\r\n");
      out.write("                        알차고 보람된 여행이 될 수 있도록 하겠습니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <br><br-->\r\n");
      out.write("                    <p class=\"a2\">오시는 길 </p><br>\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"map\" style=\"width:100%;height:350px;\"></div>\r\n");
      out.write("    \r\n");
      out.write("                    <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=19ee1aad628e3c1d1ed60863856d92c6\"></script>\r\n");
      out.write("                    <script>\r\n");
      out.write("                    var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("                        mapOption = { \r\n");
      out.write("                            center: new kakao.maps.LatLng(37.45989427195582, 127.12929871328285), // 지도의 중심좌표\r\n");
      out.write("                            level: 3 // 지도의 확대 레벨\r\n");
      out.write("                        };\r\n");
      out.write("    \r\n");
      out.write("                    // 지도를 표시할 div와  지도 옵션으로  지도를 생성합니다\r\n");
      out.write("                    var map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("    \r\n");
      out.write("                    // 지도에 마커를 표시합니다 \r\n");
      out.write("                    var marker = new kakao.maps.Marker({\r\n");
      out.write("                        map: map, \r\n");
      out.write("                        position: new kakao.maps.LatLng(37.45989427195582, 127.12929871328285)\r\n");
      out.write("                    });\r\n");
      out.write("    \r\n");
      out.write("                    // 커스텀 오버레이에 표시할 컨텐츠 입니다\r\n");
      out.write("                    // 커스텀 오버레이는 아래와 같이 사용자가 자유롭게 컨텐츠를 구성하고 이벤트를 제어할 수 있기 때문에\r\n");
      out.write("                    // 별도의 이벤트 메소드를 제공하지 않습니다 \r\n");
      out.write("                    var content = '<div class=\"wrap\">' + \r\n");
      out.write("                                '    <div class=\"info\">' + \r\n");
      out.write("                                '        <div class=\"title\">' + \r\n");
      out.write("                                '            동서울대학교' + \r\n");
      out.write("                                '            <div class=\"close\" onclick=\"closeOverlay()\" title=\"닫기\"></div>' + \r\n");
      out.write("                                '        </div>' + \r\n");
      out.write("                                '        <div class=\"body\">' + \r\n");
      out.write("                                '            <div class=\"img\">' +\r\n");
      out.write("                                '                <img src=\"images/DU.jpg\" width=\"73\" height=\"70\">' +\r\n");
      out.write("                                '           </div>' + \r\n");
      out.write("                                '            <div class=\"desc\">' + \r\n");
      out.write("                                '                <div class=\"ellipsis\">경기 성남시 수정구 복정동 423-8</div>' + \r\n");
      out.write("                                '                <div class=\"jibun ellipsis\">031-720-2900</div>' + \r\n");
      out.write("                                '                <div><a href=\"https://www.du.ac.kr/KR/index.do\" target=\"_blank\" class=\"link\">홈페이지</a></div>' + \r\n");
      out.write("                                '            </div>' + \r\n");
      out.write("                                '        </div>' + \r\n");
      out.write("                                '    </div>' +    \r\n");
      out.write("                                '</div>';\r\n");
      out.write("    \r\n");
      out.write("                    // 마커 위에 커스텀오버레이를 표시합니다\r\n");
      out.write("                    // 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다\r\n");
      out.write("                    var overlay = new kakao.maps.CustomOverlay({\r\n");
      out.write("                        content: content,\r\n");
      out.write("                        map: map,\r\n");
      out.write("                        position: marker.getPosition()       \r\n");
      out.write("                    });\r\n");
      out.write("    \r\n");
      out.write("                    // 마커를 클릭했을 때 커스텀 오버레이를 표시합니다\r\n");
      out.write("                    kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("                        overlay.setMap(map);\r\n");
      out.write("                    });\r\n");
      out.write("    \r\n");
      out.write("                    // 커스텀 오버레이를 닫기 위해 호출되는 함수입니다 \r\n");
      out.write("                    function closeOverlay() {\r\n");
      out.write("                        overlay.setMap(null);     \r\n");
      out.write("                    }\r\n");
      out.write("                    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("                <footer>\r\n");
      out.write("                    <p style=\"padding: 25px 0px 0px 0px;\">전화 : 031-720-2114</p>\r\n");
      out.write("                    <p>주소 : 경기도 성남시 수정구 복정로 76</p>\r\n");
      out.write("                </footer>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
