/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-11-08 20:37:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>BE FREE</title>\r\n");
      out.write("        <script src =\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js\"></script>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Bungee+Inline&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Varela+Round&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            body{font-family: 'Gowun Dodum', sans-serif;}\r\n");
      out.write("            ul {list-style-type: none;}\r\n");
      out.write("            a {text-decoration: none; color:black;}\r\n");
      out.write("            input {height:30px; width: 319px;}\r\n");
      out.write("\r\n");
      out.write("            .all {\r\n");
      out.write("                padding-top:15px;\r\n");
      out.write("                margin:0 auto;\r\n");
      out.write("                width:995px;\r\n");
      out.write("            }\r\n");
      out.write("            .logo{\r\n");
      out.write("                display: flex;\r\n");
      out.write("                width: 341px;\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("            .aa {\r\n");
      out.write("                /*height:1200px;*/\r\n");
      out.write("                background-color: #f5f6f7;\r\n");
      out.write("                padding-top: 50px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                top: 110px;\r\n");
      out.write("                padding-bottom: 100px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            h2 {\r\n");
      out.write("                font-size: 35px;\r\n");
      out.write("                margin: 0px;\r\n");
      out.write("                float: right;\r\n");
      out.write("                text-align: right;\r\n");
      out.write("                z-index: -1000;\r\n");
      out.write("                width: 200px;\r\n");
      out.write("                margin-top: 47px;   \r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .aa li, .a2 div { margin-left:50px;}\r\n");
      out.write("\r\n");
      out.write("            .a2 {\r\n");
      out.write("                width:500px;\r\n");
      out.write("                margin:0 auto;\r\n");
      out.write("            \r\n");
      out.write("            }\r\n");
      out.write("            .btn {text-align: center;}\r\n");
      out.write("            .ch {position: relative; top:-10px;}\r\n");
      out.write("            .btn1{\r\n");
      out.write("                background-color: rgb(89, 161, 165);\r\n");
      out.write("                width: 150px;\r\n");
      out.write("                height: 42px;\r\n");
      out.write("                border: none;\r\n");
      out.write("                font-family: 'Gowun Dodum', sans-serif;\r\n");
      out.write("                color: white;\r\n");
      out.write("                font-size: 15px;\r\n");
      out.write("            }\r\n");
      out.write("            .btn1 a{color: white; font-family: 'Gowun Dodum', sans-serif; font-size: 15px;}\r\n");
      out.write("            .btn2{\r\n");
      out.write("                background-color: rgb(114, 114, 114);\r\n");
      out.write("                width: 150px;\r\n");
      out.write("                height: 42px;\r\n");
      out.write("                border: none;\r\n");
      out.write("            }\r\n");
      out.write("            .btn2 a{color: white; font-family: 'Gowun Dodum', sans-serif; font-size: 15px;}\r\n");
      out.write("\r\n");
      out.write("			.checking{height: 20px; width: 20px;}\r\n");
      out.write("\r\n");
      out.write("            .btn-primary input[type=\"radio\"] {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("            .btn-primary input[type=\"radio\"] + span{\r\n");
      out.write("                display:inline-block;\r\n");
      out.write("                background:none;\r\n");
      out.write("                border:1px solid #a1a1a1;  \r\n");
      out.write("                padding:0px 10px;\r\n");
      out.write("                text-align:center;\r\n");
      out.write("                height:35px;\r\n");
      out.write("                line-height:33px;\r\n");
      out.write("                font-weight:500;\r\n");
      out.write("                cursor:pointer;\r\n");
      out.write("                width: 137px;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-primary input[type=\"radio\"]:checked + span{\r\n");
      out.write("                border:1px solid #23a3a7;\r\n");
      out.write("                background:#23a3a7;\r\n");
      out.write("                color:#fff;\r\n");
      out.write("            }\r\n");
      out.write(" \r\n");
      out.write("        </style>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            $(function(){\r\n");
      out.write("                $('.btn1').click(function(){\r\n");
      out.write("                    var id = document.getElementById('ID').value;\r\n");
      out.write("                    var pw = document.getElementById('PW').value;\r\n");
      out.write("                    var pwchk = document.getElementById('PWchk').value;\r\n");
      out.write("                    var name = document.getElementById('name').value;\r\n");
      out.write("                    var email = document.getElementById('email').value;\r\n");
      out.write("                    var terms1 = $(\"#check1\").is(':checked');\r\n");
      out.write("\r\n");
      out.write("                    if(id ==\"\"){\r\n");
      out.write("                        alert(\"아이디를 입력하세요\");\r\n");
      out.write("                        id.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                        \r\n");
      out.write("                    }else if(pw ==\"\"){\r\n");
      out.write("                        alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("                        pw.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                        \r\n");
      out.write("                    }else if(pwchk==\"\"){\r\n");
      out.write("                        alert(\"비밀번호확인을 입력하세요\");\r\n");
      out.write("                        pwchk.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                    }else if(name==\"\"){\r\n");
      out.write("                        alert(\"이름을 입력하세요\");\r\n");
      out.write("                        name.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                    }\r\n");
      out.write("                    if(email==\"\"){\r\n");
      out.write("                        alert(\"이메일을 입력하세요\");\r\n");
      out.write("                        document.join.email.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                    }\r\n");
      out.write("                    if(pw!=pwchk){\r\n");
      out.write("                        alert(\"입력한 2개의 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("                        document.join.pw.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                    }\r\n");
      out.write("                    if(id.length<5 || id.length>20){\r\n");
      out.write("                        alert(\"아이디는 5자이상 20자이하로 입력해주세요.\");\r\n");
      out.write("                        document.join.id.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                    }\r\n");
      out.write("                    if(!CheckEmail(email)){\r\n");
      out.write("                        alert(\"이 메일형식이 올바르지 않습니다.\");\r\n");
      out.write("                        document.join.email.focus();\r\n");
      out.write("                        exit;\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // 이메일이 잘못되었는지 확인하는 함수 \r\n");
      out.write("                function CheckEmail(str)\r\n");
      out.write("                {                                                 \r\n");
      out.write("                    var reg_email = /^([0-9a-zA-Z_\\.-]+)@([0-9a-zA-Z_-]+)(\\.[0-9a-zA-Z_-]+){1,2}$/;\r\n");
      out.write("                    if(!reg_email.test(str)) {                            \r\n");
      out.write("                        return false;         \r\n");
      out.write("                    }                            \r\n");
      out.write("                    else {                       \r\n");
      out.write("                        return true;         \r\n");
      out.write("                    }                            \r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"all\">\r\n");
      out.write("            <header>\r\n");
      out.write("                <div class=\"name\">\r\n");
      out.write("                    <a href=\"main.html\"><img class=\"logo\" src=\"images/BE_FREE.png\"></a>\r\n");
      out.write("                    <h2>회원가입</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <form method=\"post\" action=\"joinAction.jsp\">\r\n");
      out.write("                <div class=\"aa\">\r\n");
      out.write("                    <div class=\"a2\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><label>아이디</label><br><input type=\"id\" size=\"43\" id=\"ID\" name=\"userID\" placeholder=\" 5~20자의 영문 소문자, 숫자\" autofocus required></li><br>\r\n");
      out.write("                            <li><label>비밀번호</label><br><input type=\"password\" id=\"PW\" name=\"userPassword\" size=\"43\" placeholder=\" 8~16자 영문 대 소문자, 숫자, 특수문자\"required></li><br>\r\n");
      out.write("                            <li><label>비밀번호 확인</label><br><input type=\"password\" id=\"PWchk\" size=\"43\" placeholder=\" 8~16자 영문 대 소문자, 숫자, 특수문자\"required></li><br>\r\n");
      out.write("                            <li><label>이름</label><br><input type=\"name\" name=\"userName\" id=\"name\" size=\"43\"required></li><br>\r\n");
      out.write("                            <li>							\r\n");
      out.write("                                <label>성별</label><br>\r\n");
      out.write("                                <label class=\"btn btn-primary active\">\r\n");
      out.write("                                    <input type=\"radio\" name=\"userGender\" autocomplete=\"off\" value=\"남자\" checked><span>남자</span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"btn btn-primary active\">\r\n");
      out.write("                                    <input type=\"radio\" name=\"userGender\" autocomplete=\"off\" value=\"여자\"><span>여자</span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><label>이메일</label><br><input type=\"email\" id=\"email\" name=\"userEmail\" size=\"43\" class=\"userEmail\"></li><br>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <div class=\"btn\">\r\n");
      out.write("                        <button class=\"btn1\">가입하기</button> &nbsp;\r\n");
      out.write("                        <button class=\"btn2\"><a href=\"main.html\">취소</a></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
