/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-11-10 18:42:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>BE FREE</title>\r\n");
      out.write("        <script src =\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js\"></script>\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Encode+Sans+Semi+Expanded:wght@900&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Varela+Round&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/main_1.css\" />\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Gowun+Batang&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main_design.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("                //사용할 배너\r\n");
      out.write("                var $banner = $(\".banner\").find(\"ul\");\r\n");
      out.write("\r\n");
      out.write("                var $bannerWidth = $banner.children().outerWidth();//배너 이미지의 폭\r\n");
      out.write("                var $bannerHeight = $banner.children().outerHeight(); // 높이\r\n");
      out.write("                var $bannerLength = $banner.children().length;//배너 이미지의 갯수\r\n");
      out.write("                var rollingId;\r\n");
      out.write("\r\n");
      out.write("                //정해진 초마다 함수 실행\r\n");
      out.write("                rollingId = setInterval(function() { rollingStart(); }, 5000);//다음 이미지로 롤링 애니메이션 할 시간차\r\n");
      out.write("\r\n");
      out.write("                //마우스 오버시 롤링을 멈춘다.\r\n");
      out.write("                banner.mouseover(function(){\r\n");
      out.write("                    //중지\r\n");
      out.write("                    clearInterval(rollingId);\r\n");
      out.write("                    $(this).css(\"cursor\", \"pointer\");\r\n");
      out.write("                });\r\n");
      out.write("                //마우스 아웃되면 다시 시작\r\n");
      out.write("                banner.mouseout(function(){\r\n");
      out.write("                    rollingId = setInterval(function() { rollingStart(); }, 5000);\r\n");
      out.write("                    $(this).css(\"cursor\", \"default\");\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                function rollingStart() {\r\n");
      out.write("                    $banner.css(\"width\", $bannerWidth * $bannerLength + \"px\");\r\n");
      out.write("                    $banner.css(\"height\", $bannerHeight + \"px\");\r\n");
      out.write("                    //alert(bannerHeight);\r\n");
      out.write("                    //배너의 좌측 위치를 옮겨 준다.\r\n");
      out.write("                    $banner.animate({left: - $bannerWidth + \"px\"}, 1500, function() { //숫자는 롤링 진행되는 시간이다.\r\n");
      out.write("                        //첫번째 이미지를 마지막 끝에 복사(이동이 아니라 복사)해서 추가한다.\r\n");
      out.write("                        $(this).append(\"<li>\" + $(this).find(\"li:first\").html() + \"</li>\");\r\n");
      out.write("                        //뒤로 복사된 첫번재 이미지는 필요 없으니 삭제한다.\r\n");
      out.write("                        $(this).find(\"li:first\").remove();\r\n");
      out.write("                        //다음 움직임을 위해서 배너 좌측의 위치값을 초기화 한다.\r\n");
      out.write("                        $(this).css(\"left\", 0);\r\n");
      out.write("                        //이 과정을 반복하면서 계속 롤링하는 배너를 만들 수 있다.\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            }); \r\n");
      out.write("\r\n");
      out.write("            /* Demo purposes only */\r\n");
      out.write("            $(\".hover\").mouseleave(\r\n");
      out.write("            function () {\r\n");
      out.write("                $(this).removeClass(\"hover\");\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    	");
 // 메인 페이지로 이동했을 때 세션에 값이 담겨있는지 체크
			String userID = null;
			if(session.getAttribute("userID") != null){
				userID = (String)session.getAttribute("userID");
			}
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("        <div class=\"all\">\r\n");
      out.write("	\r\n");
      out.write("            <div class=\"main\">\r\n");
      out.write("                    <header>\r\n");
      out.write("                        <div class=\"name\">\r\n");
      out.write("                    ");

						// 로그인 하지 않았을 때 보여지는 화면
						if(userID == null){
					
      out.write("\r\n");
      out.write("                            <ul class=\"login\">\r\n");
      out.write("                                <li><a href=\"login.jsp\">로그인</a></li> &nbsp;\r\n");
      out.write("                                <li><a href=\"clause.jsp\">회원가입</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                    ");

						// 로그인이 되어 있는 상태에서 보여주는 화면
						}else{
					
      out.write("    \r\n");
      out.write("                            <ul class=\"login\">\r\n");
      out.write("                                <li><a href=\"logoutAction.jsp\">로그아웃</a></li> &nbsp;\r\n");
      out.write("                                <li><a href=\"main.jsp\">회원관리</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            \r\n");
      out.write("                    ");

						}
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("                            <nav>\r\n");
      out.write("                                <div class=\"title_menu\">\r\n");
      out.write("                                    <a href=\"main.jsp\"><img class=\"logo\" src=\"images/BE_FREE.png\"></a>\r\n");
      out.write("                                    <ul id=\"main-menu\">\r\n");
      out.write("                                        <li><a href=\"회사소개.html\">BE FREE란</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">관광지</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">추천여행지</a>\r\n");
      out.write("                                            <ul id=\"sub-menu\">\r\n");
      out.write("                                                <li><a href=\"문의하기.html\">추천여행지</a></li>\r\n");
      out.write("                                                <li><a href=\"공지사항.html\">추천여행일정</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li><a href=\"#\">일정만들기</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">게시판</a>\r\n");
      out.write("                                            <ul id=\"sub-menu\">\r\n");
      out.write("                                                <li><a href=\"notice.jsp\">공지사항</a></li>\r\n");
      out.write("                                                <li><a href=\"Q&A.jsp\">Q&A</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li><a href=\"#\">나의 저장소</a>\r\n");
      out.write("                                            <ul id=\"sub-menu\">\r\n");
      out.write("                                                <li><a href=\"나의찜목록.html\">나의 찜 목록</a></li>\r\n");
      out.write("                                                <li><a href=\"나의여행일정.html\">나의 여행 일정</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                            <div class=\"hd\">\r\n");
      out.write("                                <div class=\"ment\">\r\n");
      out.write("                                    <p class=\"typing-txt\"> 떠나자, 제주도로. </p> \r\n");
      out.write("                                    <p class=\"typing\"></p> \r\n");
      out.write("                                    <div class=\"banner_a\">\r\n");
      out.write("                                        <div class=\"banner\">\r\n");
      out.write("                                            <ul> \r\n");
      out.write("                                                <li> <img src=\"images/jejudo/jejudo2.jpg\" width=\"1400px\" height=\"600px\"></li>\r\n");
      out.write("                                                <li> <img src=\"images/jejudo/jejudo8.jpg\" width=\"1400px\" height=\"600px\"></li>\r\n");
      out.write("                                                <li> <img src=\"images/jejudo/jejudo9.jpg\" width=\"1400px\" height=\"600px\"></li>\r\n");
      out.write("                                                <li> <img src=\"images/jejudo/jejudo10.jpg\" width=\"1400px\" height=\"600px\"></li>\r\n");
      out.write("                                                <li> <img src=\"images/jejudo/jejudo11.jpg\" width=\"1400px\" height=\"600px\"></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--<div class=\"slider-btns\" id=\"next\"><span>▶</span></div>\r\n");
      out.write("                                <div class=\"slider-btns\" id=\"previous\"><span>◀</span></div>-->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </header>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"se\">\r\n");
      out.write("            <section>\r\n");
      out.write("                <div class=\"se2\">\r\n");
      out.write("                <div class=\"sa sa-up\">\r\n");
      out.write("                    <p>간편하게 지금 바로!<br><spen class=\"BEST\">BEST 추천 여행 일정</spen></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item_list\">\r\n");
      out.write("                    <dd class=\"recommend_plan\">\r\n");
      out.write("                        <dl class=\"item_section\">\r\n");
      out.write("                            <dt class=\"item_top\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"images/jejudo/jejudo7.jpg\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                    <p class=\"item_title\">TITLE</p>\r\n");
      out.write("                                    <p class=\"item_plan\">1박2일</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dt class=\"item_btm_like\"><a href=\"#\"><img src=\"images/heart.png\" width=\"30px\" height=\"30px\"></a></dt>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl class=\"item_section\">\r\n");
      out.write("                            <dt class=\"item_top\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"images/jejudo/jejudo4.jpg\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                    <p class=\"item_title\">TITLE</p>\r\n");
      out.write("                                    <p class=\"item_plan\">1박2일</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dt class=\"item_btm_like\"><a href=\"#\"><img src=\"images/heart.png\" width=\"30px\" height=\"30px\"></a></dt>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl class=\"item_section\">\r\n");
      out.write("                            <dt class=\"item_top\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"images/jejudo/jejudo5.jpg\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                    <p class=\"item_title\">TITLE</p>\r\n");
      out.write("                                    <p class=\"item_plan\">1박2일</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dt class=\"item_btm_like\"><a href=\"#\"><img src=\"images/heart.png\" width=\"30px\" height=\"30px\"></a></dt>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl class=\"item_section\">\r\n");
      out.write("                            <dt class=\"item_top\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"images/jejudo/jejudo6.jpg\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                    <p class=\"item_title\">TITLE</p>\r\n");
      out.write("                                    <p class=\"item_plan\">1박2일</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dt class=\"item_btm_like\"><a href=\"#\"><img src=\"images/heart.png\" width=\"30px\" height=\"30px\"></a></dt>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"item_list2\">\r\n");
      out.write("                    <dd class=\"recommend_travle\">\r\n");
      out.write("                        <table class=\"table_travle\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"travle\">\r\n");
      out.write("                                    <dl class=\"item_section2\">\r\n");
      out.write("                                        <dt class=\"item_top\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img src=\"images/jejudo/jejudo7.jpg\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                                <p class=\"item_title2\">#TITLE</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </dt>\r\n");
      out.write("                                        <dt class=\"item_btm_like2\"><a href=\"#\"><img src=\"images/heart.png\" width=\"30px\" height=\"30px\"></dt>\r\n");
      out.write("                                    </dl>\r\n");
      out.write("                                    <dl class=\"item_section2\">\r\n");
      out.write("                                        <dt class=\"item_top\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img src=\"images/jejudo/jejudo4.jpg\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                                <p class=\"item_title2\">#TITLE</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </dt>\r\n");
      out.write("                                        <dt class=\"item_btm_like2\"><a href=\"#\"><img src=\"images/heart.png\" width=\"30px\" height=\"30px\"></dt>\r\n");
      out.write("                                    </dl>\r\n");
      out.write("                                    <dl class=\"item_section2\">\r\n");
      out.write("                                        <dt class=\"item_top\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img src=\"images/jejudo/jejudo5.jpg\" width=\"200px\" height=\"200px\" class=\"item_img\">\r\n");
      out.write("                                                <p class=\"item_title2\">#TITLE</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </dt>\r\n");
      out.write("                                        <dt class=\"item_btm_like2\"><a href=\"#\"><img src=\"images/heart.png\" width=\"30px\" height=\"30px\"></dt>\r\n");
      out.write("                                    </dl>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"hash\">\r\n");
      out.write("                                    <p class=\"hash1\">#인생_여행지</p>\r\n");
      out.write("                                    <p class=\"hash2\">#헐_여기어디</p>\r\n");
      out.write("                                    <p class=\"recommend_travle_hash\">BEST 추천 여행지</p>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"service\">\r\n");
      out.write("                    <dd class=\"service_item\">\r\n");
      out.write("                        <dl class=\"item_section3\">\r\n");
      out.write("                            <dt class=\"item_top_service\">\r\n");
      out.write("                                <a href=\"https://www.visitjeju.net/kr/bigdatamap/\">\r\n");
      out.write("                                <img src=\"images/service.png\" height=\"200px\"></a>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </div>\r\n");
      out.write("                <script>\r\n");
      out.write("                // Scroll Animation (sa, 스크롤 애니메이션)\r\n");
      out.write("                const saTriggerMargin = 300;\r\n");
      out.write("                const saElementList = document.querySelectorAll('.sa');\r\n");
      out.write("\r\n");
      out.write("                const saFunc = function() {\r\n");
      out.write("                    for (const element of saElementList) {\r\n");
      out.write("                    if (!element.classList.contains('show')) {\r\n");
      out.write("                        if (window.innerHeight > element.getBoundingClientRect().top + saTriggerMargin) {\r\n");
      out.write("                        element.classList.add('show');\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                window.addEventListener('load', saFunc);\r\n");
      out.write("                window.addEventListener('scroll', saFunc);\r\n");
      out.write("                </script>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"fotal\">\r\n");
      out.write("                    <div class=\"f\">\r\n");
      out.write("                        <div class=fi>\r\n");
      out.write("                            <figure class=\"snip1477\" style=\"float: right;\">\r\n");
      out.write("                                <img src=\"images/jejudo/jejudo5.jpg\" width=\"300px\" height=\"300px\"  />\r\n");
      out.write("                                <div class=\"title\">\r\n");
      out.write("                                  <div>\r\n");
      out.write("                                    <h2>추천여행지</h2>\r\n");
      out.write("                                    <h4>바로가기</h4>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <figcaption>\r\n");
      out.write("                                  <p>여행지를 고르기 힘들다면?<br><br>추천여행지를 통해 골라보세요.<br></p>\r\n");
      out.write("                                </figcaption>\r\n");
      out.write("                                <a href=\"제품소개.html\"></a>\r\n");
      out.write("                              </figure>\r\n");
      out.write("                             \r\n");
      out.write("                              <figure class=\"snip1477\"><img src=\"images/jejudo/jejudo6.jpg\" width=\"300px\" height=\"300px\" alt=\"sample35\" />\r\n");
      out.write("                                <div class=\"title\">\r\n");
      out.write("                                  <div>\r\n");
      out.write("                                    <h2>일정만들기</h2>\r\n");
      out.write("                                    <h4>만들러가기</h4>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <figcaption>\r\n");
      out.write("                                  <p>나만의 여행을 떠나고 싶을 때.<br><br>자신의 손으로 만들어보세요.</p>\r\n");
      out.write("                                </figcaption>\r\n");
      out.write("                                <a href=\"어플소개.html\"></a>\r\n");
      out.write("                              </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    <!--\r\n");
      out.write("                            <div class=\"vd\">\r\n");
      out.write("                                <video src=\"media/Painting.mp4\" controls></video>\r\n");
      out.write("                            </div>-->\r\n");
      out.write("                        </div> \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("   \r\n");
      out.write("            </section>\r\n");
      out.write("            \r\n");
      out.write("            <footer>\r\n");
      out.write("                <p style=\"padding: 25px 0px 0px 0px;\">전화 : 031-720-2114</p>\r\n");
      out.write("                <p>주소 : 경기도 성남시 수정구 복정로 76</p>\r\n");
      out.write("            </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
